const NPC_ID = Object.freeze({
  TWINS_BOSS: 'npc-twins-boss-1a2b',
  TWINS_DOGS: 'npc-twins-dogs-3c4d',
  TWINS_WEAPONS: 'npc-twins-weapons-5e6f',
  SAIL_RIPPER: 'npc-sail-ripper-7a8b',
  BOW_BREAKER: 'npc-bow-breaker-9c0d',
  REEF_GUARDIANS: 'npc-reef-guardians-1e2f',
  REEF_GUARDIAN_LARGE: 'npc-reef-guardian-large-3a4b',
  REEF_GUARDIAN_MEDIUM: 'npc-reef-guardian-medium-5c6d',
  REEF_GUARDIAN_MEDIUM_1: 'npc-reef-guardian-medium-1-7e8f',
  REEF_GUARDIAN_MEDIUM_2: 'npc-reef-guardian-medium-2-9a0b',
  REEF_GUARDIAN_SMALL: 'npc-reef-guardian-small-1c2d',
  REEF_GUARDIAN_SMALL_1: 'npc-reef-guardian-small-1-3e4f',
  REEF_GUARDIAN_SMALL_2: 'npc-reef-guardian-small-2-5a6b',
  REEF_GUARDIAN_BEAR: 'npc-reef-guardian-bear-7c8d',
  REEF_GUARDIAN_CAT: 'npc-reef-guardian-cat-9e0f',
  REEF_GUARDIAN_MAGE: 'npc-reef-guardian-mage-1a2b',
  TALERIA_BOSS: 'npc-taleria-boss-3c4d',
  TALERIA_MAGE: 'npc-taleria-mage-5e6f',
  TALERIA_SIRENS: 'npc-taleria-sirens-7a8b',
  TALERIA_BEHEMOTH: 'npc-taleria-behemoth-9c0d',
  TRASH_SWASHBUCKLER: 'npc-trash-swashbuckler-1e2f',
});

const NPC_DEFINITIONS = new Map([
  [NPC_ID.TWINS_BOSS, { name: "Boss", icon: "🔥❄️", color: "#ff7f50" }],
  [NPC_ID.TWINS_DOGS, { name: "Dogs", icon: "🐕", color: "#ff4500" }],
  [NPC_ID.TWINS_WEAPONS, { name: "Weapon", icon: "⚔️", color: "#a9a9a9" }],
  [NPC_ID.SAIL_RIPPER, { name: "Sail Ripper", icon: "🐦", color: "#00ced1" }],
  [NPC_ID.BOW_BREAKER, { name: "Bow Breaker", icon: "🐢", color: "#32cd32" }],
  [NPC_ID.REEF_GUARDIANS, { name: "Reef Guardians", icon: "🪸", color: "#f08080" }],
  [NPC_ID.REEF_GUARDIAN_LARGE, { name: "Large", icon: "🪸", color: "#cd5c5c" }],
  [NPC_ID.REEF_GUARDIAN_MEDIUM, { name: "Medium", icon: "🪸", color: "#fa8072" }],
  [NPC_ID.REEF_GUARDIAN_MEDIUM_1, { name: "Medium #1", icon: "🪸", color: "#fa8072" }],
  [NPC_ID.REEF_GUARDIAN_MEDIUM_2, { name: "Medium #2", icon: "🪸", color: "#e9967a" }],
  [NPC_ID.REEF_GUARDIAN_SMALL, { name: "Small", icon: "🪸", color: "#ffa07a" }],
  [NPC_ID.REEF_GUARDIAN_SMALL_1, { name: "Small #1", icon: "🪸", color: "#ffa07a" }],
  [NPC_ID.REEF_GUARDIAN_SMALL_2, { name: "Small #2", icon: "🪸", color: "#ffb6c1" }],
  [NPC_ID.REEF_GUARDIAN_BEAR, { name: "Bear", icon: "🐻", color: "#8b4513" }],
  [NPC_ID.REEF_GUARDIAN_CAT, { name: "Cat", icon: "🐯", color: "#d2691e" }],
  [NPC_ID.REEF_GUARDIAN_MAGE, { name: "Mage", icon: "🧙", color: "#9370db" }],
  [NPC_ID.TALERIA_BOSS, { name: "Taleria", icon: "🌊", color: "#1e90ff" }],
  [NPC_ID.TALERIA_MAGE, { name: "Mage", icon: "🧙", color: "#9370db" }],
  [NPC_ID.TALERIA_SIRENS, { name: "Sirens", icon: "🧜‍♀️", color: "#ff69b4" }],
  [NPC_ID.TALERIA_BEHEMOTH, { name: "Sea Behemoth", icon: "👹", color: "#4682b4" }],
  [NPC_ID.TRASH_SWASHBUCKLER, { name: "Swashbuckler", icon: "🏴‍☠️", color: "#ffd700" }],
]);