// ============================================================
// DSR HM Progression — Role Tag to Player ID Mapping
// ============================================================

const ROLE_TAGS = Object.freeze({
  BRIDGE_DPS: 'bridge-dps',
  REEF_DPS: 'reef-dps',
  REEF_GROUP_1: 'reef-group-1',
  REEF_GROUP_2: 'reef-group-2',
  REEF_BACKUP: 'reef-backup',
  BRIDGE_BACKUP: 'bridge-backup',
  DPS: 'dps',
  HEALERS: 'healers',
  TANKS: 'tanks',
  LEVER_PULLERS: 'lever-pullers',
  TWINS_LARGE_GROUP: 'twins-large-group',
  TWINS_SMALL_GROUP: 'twins-small-group',
});

const ROLE_TAG_MAP = new Map([
  [ROLE_TAGS.BRIDGE_DPS, [PLAYER_ID.DPS6, PLAYER_ID.DPS7]],
  [ROLE_TAGS.REEF_DPS, [PLAYER_ID.DPS1, PLAYER_ID.DPS4, PLAYER_ID.DPS6, PLAYER_ID.DPS7]],
  [ROLE_TAGS.REEF_GROUP_1, [PLAYER_ID.DPS1, PLAYER_ID.DPS4]],
  [ROLE_TAGS.REEF_GROUP_2, [PLAYER_ID.DPS6, PLAYER_ID.DPS7]],
  [ROLE_TAGS.REEF_BACKUP, [PLAYER_ID.DPS3, PLAYER_ID.DPS5]],
  [ROLE_TAGS.BRIDGE_BACKUP, [PLAYER_ID.DPS3, PLAYER_ID.DPS5]],
  [ROLE_TAGS.DPS, [PLAYER_ID.DPS1, PLAYER_ID.DPS2, PLAYER_ID.DPS3, PLAYER_ID.DPS4, PLAYER_ID.DPS5, PLAYER_ID.DPS6, PLAYER_ID.DPS7, PLAYER_ID.DPS8]],
  [ROLE_TAGS.HEALERS, [PLAYER_ID.H1, PLAYER_ID.H2]],
  [ROLE_TAGS.TANKS, [PLAYER_ID.MT, PLAYER_ID.OT]],
  [ROLE_TAGS.LEVER_PULLERS, [PLAYER_ID.DPS7, PLAYER_ID.H2, PLAYER_ID.MT]],
  [ROLE_TAGS.TWINS_LARGE_GROUP, [PLAYER_ID.DPS1, PLAYER_ID.DPS2, PLAYER_ID.DPS3, PLAYER_ID.DPS4, PLAYER_ID.DPS5, PLAYER_ID.DPS6, PLAYER_ID.DPS7, PLAYER_ID.H1]],
  [ROLE_TAGS.TWINS_SMALL_GROUP, [PLAYER_ID.DPS8, PLAYER_ID.H2]],
]);